### ISSUE TITLE
Automatically hydrate new elements

### ISSUE THREAD

**Issue by lekoala** [WebReflection/nonchalance#7]
Hi there!

Very nice library you got there. In your opinion, what would be the best would to automatically upgrade any injected element (through ajax calls, dom manipulation, etc) ?

**Comment by WebReflection** [comment]
you can create a registry with plain CSS selectors and refer a class per each selector ... when the node gets connected you `new Class(node)` and you're done.

You can use [qsa-observer](https://github.com/WebReflection/qsa-observer#readme) to do so and update the `query` array whenever you want to register something new, the rest should do automatically.

I might also write a helper in here for the sake of demo, also because I think this use case is more than frequent or desired.

**Comment by lekoala** [comment]
yes that works indeed nicely !

**Comment by WebReflection** [comment]
The `/selector` export (796 bytes) allows live definition of any CSS selector so that the related class will automatically upgrade any element that matches that selector.

Please note that such selector should be *as unique as possible* otherwise surprises might happen. Use specific classes or `data-` attributes to describe best your selector.

```js
import createRegistry from 'nonchalance/core';
import { define } from 'nonchalance/selector';

const { HTML } = createRegistry();
const Special = define('[data-comp="special"]', class extends HTML.Div {
  constructor(...args) {
    super(...args);
    this.textContent = 'I am special!';
  }
});

// will contain "I am special!" text once live
document.body.innerHTML = `<div data-comp="special"></div>`;
```

**Comment by WebReflection** [comment]
@lekoala I hope this new entry solves your issue ... keep in mind you can still do `new Special` whenever you like and the registry could be actually any registry, not just core.
